name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:  # to allow manual re-runs


jobs:
  linting:
    name: "Perform linting checks"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: "actions/checkout@v4"
      - name: Install poetry
        run: pipx install poetry
      - uses: "actions/setup-python@v5"
        id: setup-python
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'poetry'
      - name: "Install dependencies"
        run: |
          poetry install
      - name: Check Poetry Python version
        run: poetry env info               
